[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-application"
version = "1.0.0"
authors = [{name = "Волькович М.А."}]
description = "Пример приложения для CI/CD"
readme = "README.md"
requires-python = ">=3.9"